/**
 * Mock data for frontend development.
 * Clearly separated from production API logic.
 * Replace with real backend responses when available.
 */

export const mockMatches = [
  {
    id: 'match-1',
    lostItem: {
      id: 'lost-1',
      title: 'Black Casio Scientific Calculator',
      description: 'Casio fx-991EX scientific calculator with my name "Ravi" written on the back in marker.',
      category: 'calculators',
      location: 'Central Library',
      date: '2026-07-28',
      image: null,
      reportedAt: '2026-07-28T14:30:00Z',
    },
    foundItem: {
      id: 'found-1',
      title: 'Casio Calculator Found in Library',
      description: 'Black Casio scientific calculator found on the 2nd floor reading area, has a name written on the back.',
      category: 'calculators',
      location: 'Central Library',
      date: '2026-07-28',
      image: null,
      reportedAt: '2026-07-28T16:15:00Z',
    },
    confidence: 94,
    reasons: [
      'Same item type: scientific calculator',
      'Matching brand: Casio',
      'Same location: Central Library',
      'Reports within 2 hours of each other',
      'Description mentions name marking',
    ],
    status: 'pending',
  },
  {
    id: 'match-2',
    lostItem: {
      id: 'lost-2',
      title: 'Blue Hydroflask Water Bottle',
      description: 'Navy blue 32oz Hydroflask with stickers on it. Lost somewhere around the cafeteria.',
      category: 'water-bottles',
      location: 'Main Cafeteria',
      date: '2026-07-27',
      image: null,
      reportedAt: '2026-07-27T13:00:00Z',
    },
    foundItem: {
      id: 'found-2',
      title: 'Blue Water Bottle with Stickers',
      description: 'Large blue insulated water bottle found near the cafeteria exit. Has several laptop-style stickers.',
      category: 'water-bottles',
      location: 'Main Cafeteria',
      date: '2026-07-27',
      image: null,
      reportedAt: '2026-07-27T17:45:00Z',
    },
    confidence: 87,
    reasons: [
      'Same item type: water bottle',
      'Matching colour: blue',
      'Same location: Main Cafeteria',
      'Both mention stickers as distinguishing feature',
    ],
    status: 'pending',
  },
  {
    id: 'match-3',
    lostItem: {
      id: 'lost-3',
      title: 'College ID Card — Priya Sharma',
      description: 'My college ID card, name is Priya Sharma, B.Tech CSE 3rd year. Probably dropped near the lecture halls.',
      category: 'id-cards',
      location: 'Lecture Hall A',
      date: '2026-07-26',
      image: null,
      reportedAt: '2026-07-26T10:20:00Z',
    },
    foundItem: {
      id: 'found-3',
      title: 'Student ID Card Found',
      description: 'Found a student ID card on the ground outside Lecture Hall B. Name visible on the card, CSE department.',
      category: 'id-cards',
      location: 'Lecture Hall B',
      date: '2026-07-26',
      image: null,
      reportedAt: '2026-07-26T11:05:00Z',
    },
    confidence: 76,
    reasons: [
      'Same item type: ID card',
      'Same department mentioned: CSE',
      'Nearby locations: Lecture Hall A and B',
      'Reports within 1 hour',
    ],
    status: 'pending',
  },
];

export const mockSearchResults = [
  {
    id: 'found-1',
    title: 'Casio Calculator Found in Library',
    description: 'Black Casio scientific calculator found on the 2nd floor reading area.',
    category: 'calculators',
    location: 'Central Library',
    date: '2026-07-28',
    type: 'found',
    status: 'unclaimed',
    image: null,
  },
  {
    id: 'found-4',
    title: 'Black Wallet Found in Canteen',
    description: 'Small black leather wallet found under a table in the main canteen. Contains some cards.',
    category: 'wallets',
    location: 'Canteen',
    date: '2026-07-27',
    type: 'found',
    status: 'unclaimed',
    image: null,
  },
  {
    id: 'lost-5',
    title: 'Silver Laptop Charger',
    description: 'Dell 65W laptop charger, silver color. Left in Computer Lab 1 during the afternoon session.',
    category: 'chargers',
    location: 'Computer Lab 1',
    date: '2026-07-26',
    type: 'lost',
    status: 'searching',
    image: null,
  },
];

export const mockDashboard = {
  totalReports: 128,
  recovered: 46,
  pending: 82,
  aiMatches: 12,
  recoveryRate: 36,
  topCategory: 'Electronics',
  topLocation: 'Central Library',
  recentReports: [
    { id: 'lost-1', title: 'Black Casio Scientific Calculator', type: 'lost', status: 'matched', location: 'Central Library', date: '18 minutes ago' },
    { id: 'found-2', title: 'Blue Water Bottle with Stickers', type: 'found', status: 'matched', location: 'Main Cafeteria', date: '4 hours ago' },
    { id: 'lost-4', title: 'Black Leather Wallet', type: 'lost', status: 'searching', location: 'Canteen', date: '1 day ago' },
    { id: 'found-5', title: 'White Earphones Case', type: 'found', status: 'unclaimed', location: 'Lecture Hall A', date: '1 day ago' },
    { id: 'lost-6', title: 'Hostel Room Key', type: 'lost', status: 'recovered', location: 'Sports Complex', date: '2 days ago' },
  ],
  chartData: [
    { name: 'Mon', lost: 8, found: 5, recovered: 3 },
    { name: 'Tue', lost: 12, found: 9, recovered: 6 },
    { name: 'Wed', lost: 6, found: 11, recovered: 7 },
    { name: 'Thu', lost: 10, found: 7, recovered: 4 },
    { name: 'Fri', lost: 15, found: 12, recovered: 8 },
    { name: 'Sat', lost: 4, found: 6, recovered: 5 },
    { name: 'Sun', lost: 3, found: 4, recovered: 3 },
  ],
  categoryData: [
    { name: 'Electronics', value: 32 },
    { name: 'ID Cards', value: 24 },
    { name: 'Wallets', value: 18 },
    { name: 'Bottles', value: 14 },
    { name: 'Keys', value: 12 },
    { name: 'Other', value: 28 },
  ],
};

export const mockItemDetail = {
  id: 'found-1',
  title: 'Casio Calculator Found in Library',
  description: 'Black Casio scientific calculator found on the 2nd floor reading area near window seats. Has a name written on the back in blue marker. Model appears to be fx-991EX.',
  category: 'calculators',
  location: 'Central Library',
  date: '2026-07-28',
  type: 'found',
  status: 'unclaimed',
  reportedAt: '2026-07-28T16:15:00Z',
  image: null,
  aiAnalysis: {
    detectedType: 'Scientific Calculator',
    detectedBrand: 'Casio',
    detectedColour: 'Black',
    visibleText: 'Ravi (handwritten)',
    additionalNotes: 'Calculator appears to be in working condition. Battery compartment intact.',
  },
};
